[tasks.run-bench]
description = "Run Rust benchmarks"
command = "cargo"
args = ["bench"]

[tasks.visualize]
description = "Run the Python script for drawing the graph"
command = "python3"
args = ["plot_results.py"]

[tasks.pipeline]
description = "Complete process: Measurement -> Visualization"
dependencies = ["run-bench", "visualize"]

[tasks.default]
alias = "pipeline"